#!/usr/bin/env python3
"""
export_neo4j.py — Export Ontology to Neo4j Cypher
====================================================
Generates Cypher statements to import a merged ontology into Neo4j.
Creates nodes for classes and instances, edges for inheritance, relations,
and instance_of links.

Usage:
    python scripts/export_neo4j.py private_enterprise/deloitte-china-consulting/output/merged_ontology.json
    python scripts/export_neo4j.py merged.json -o output/neo4j_import.cypher
    cat output/neo4j_import.cypher | cypher-shell -u neo4j -p $NEO4J_PASSWORD
"""

import json
import sys
import io
import argparse
from pathlib import Path

if sys.stdout.encoding != 'utf-8':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')


def escape_cypher(s):
    """Escape a string for Cypher."""
    if s is None:
        return ""
    return str(s).replace("\\", "\\\\").replace("'", "\\'").replace('"', '\\"')


def generate_cypher(data):
    """Generate Cypher import statements."""
    classes = data.get("classes", [])
    relations = data.get("relations", [])
    instances = data.get("sample_instances", [])
    attributes = data.get("attributes", [])
    axioms = data.get("axioms", [])

    lines = []
    lines.append("// ══════════════════════════════════════════════════════════")
    lines.append(f"// {data.get('metadata', {}).get('name', 'Ontology')} — Neo4j Import")
    lines.append(f"// Generated by export_neo4j.py")
    lines.append("// ══════════════════════════════════════════════════════════")
    lines.append("")

    # Clean slate
    lines.append("// Clear existing ontology data (optional)")
    lines.append("// MATCH (n) WHERE n:Class OR n:Instance OR n:Relation DETACH DELETE n;")
    lines.append("")

    # Constraints
    lines.append("// Constraints")
    lines.append("CREATE CONSTRAINT IF NOT EXISTS FOR (c:Class) REQUIRE c.id IS UNIQUE;")
    lines.append("CREATE CONSTRAINT IF NOT EXISTS FOR (i:Instance) REQUIRE i.id IS UNIQUE;")
    lines.append("")

    # Build attribute map for enriching class nodes
    attr_by_owner = {}
    for a in attributes:
        attr_by_owner.setdefault(a.get("owner_class", ""), []).append(a)

    # Class nodes
    lines.append("// ── Class Nodes ──")
    for c in classes:
        cid = escape_cypher(c["id"])
        props = {
            "id": c["id"],
            "label_en": c.get("label_en", c["id"]),
            "label_zh": c.get("label_zh", ""),
            "layer": c.get("source_layer", ""),
            "domain": c.get("domain", ""),
            "abstract": c.get("abstract", False),
            "definition_en": (c.get("definition_en") or "")[:200],
            "definition_zh": (c.get("definition") or "")[:200],
        }
        if c.get("alias_of"):
            props["alias_of"] = c["alias_of"]

        # Add attribute names as a list property
        attrs = attr_by_owner.get(c["id"], [])
        if attrs:
            props["attributes"] = [a["id"] for a in attrs]

        props_str = ", ".join(f'{k}: {json.dumps(v, ensure_ascii=False)}' for k, v in props.items())
        lines.append(f"MERGE (c:Class {{{props_str}}});")

    lines.append("")

    # Inheritance edges
    lines.append("// ── Inheritance (SUBCLASS_OF) ──")
    for c in classes:
        parent = c.get("parent")
        if parent:
            cid = escape_cypher(c["id"])
            pid = escape_cypher(parent)
            lines.append(f"MATCH (child:Class {{id: '{cid}'}}), (parent:Class {{id: '{pid}'}}) MERGE (child)-[:SUBCLASS_OF]->(parent);")

    # Alias edges
    lines.append("")
    lines.append("// ── Alias (EQUIVALENT_CLASS) ──")
    for c in classes:
        alias = c.get("alias_of")
        if alias:
            cid = escape_cypher(c["id"])
            aid = escape_cypher(alias)
            lines.append(f"MATCH (a:Class {{id: '{cid}'}}), (b:Class {{id: '{aid}'}}) MERGE (a)-[:EQUIVALENT_CLASS]->(b);")

    lines.append("")

    # Relation edges (as typed relationships between class nodes)
    lines.append("// ── Relations ──")
    for r in relations:
        domain = r.get("domain")
        rng = r.get("range")
        if not domain or not rng:
            continue
        rid = r["id"].upper()
        props = {
            "rid": r["id"],
            "cardinality": r.get("cardinality", ""),
            "definition": (r.get("definition_en") or r.get("definition") or "")[:100],
        }
        props_str = ", ".join(f'{k}: {json.dumps(v, ensure_ascii=False)}' for k, v in props.items())
        did = escape_cypher(domain)
        rnid = escape_cypher(rng)
        lines.append(f"MATCH (d:Class {{id: '{did}'}}), (r:Class {{id: '{rnid}'}}) MERGE (d)-[:{rid} {{{props_str}}}]->(r);")

    lines.append("")

    # Instance nodes and instance_of edges
    if instances:
        lines.append("// ── Instance Nodes ──")
        for inst in instances:
            iid = escape_cypher(inst["id"])
            props = {
                "id": inst["id"],
                "label": inst.get("label", inst["id"]),
                "label_zh": inst.get("label_zh", ""),
                "type": inst.get("type", ""),
            }
            props_str = ", ".join(f'{k}: {json.dumps(v, ensure_ascii=False)}' for k, v in props.items())
            lines.append(f"MERGE (i:Instance {{{props_str}}});")

        lines.append("")
        lines.append("// ── Instance-of Edges ──")
        for inst in instances:
            itype = inst.get("type")
            if itype:
                iid = escape_cypher(inst["id"])
                tid = escape_cypher(itype)
                lines.append(f"MATCH (i:Instance {{id: '{iid}'}}), (c:Class {{id: '{tid}'}}) MERGE (i)-[:INSTANCE_OF]->(c);")

    lines.append("")
    lines.append(f"// Total: {len(classes)} classes, {len(relations)} relations, {len(instances)} instances")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Export ontology to Neo4j Cypher")
    parser.add_argument("input", help="Path to merged_ontology.json")
    parser.add_argument("-o", "--output", help="Output .cypher file path")
    args = parser.parse_args()

    input_path = Path(args.input).resolve()
    if args.output:
        output_path = Path(args.output).resolve()
    else:
        output_path = input_path.parent / "neo4j_import.cypher"

    with open(input_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    cypher = generate_cypher(data)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(cypher)

    # Stats
    cls_count = len(data.get("classes", []))
    rel_count = len(data.get("relations", []))
    inst_count = len(data.get("sample_instances", []))
    stmt_count = cypher.count(";")

    print(f"  [OK] {output_path}")
    print(f"       {stmt_count} Cypher statements ({cls_count} classes, {rel_count} relations, {inst_count} instances)")


if __name__ == "__main__":
    main()
