#!/usr/bin/env python3
"""
generate_glossary.py — Generate machine-derived glossary fragments under
docs-site/glossary/_generated/ from the canonical ontology JSON.

v0 scope: L1 classes table only. The fragment is meant to be embedded into
a human-authored page via mkdocs-include-markdown-plugin's `{% include-markdown %}`
directive, so authors keep their narrative ("guide" paragraphs) while the
class list itself stays in lock-step with the JSON.

Run after editing l1-core/universal_ontology_v1.json. Pre-commit + CI will
diff this output against the tracked file (Phase 4.x follow-up) to catch
regen-skipped commits.
"""

import io
import json
import sys
from pathlib import Path

if sys.stdout.encoding != "utf-8":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parent.parent
L1_PATH = ROOT / "l1-core" / "universal_ontology_v1.json"
OUT_DIR = ROOT / "docs-site" / "glossary" / "_generated"
OUT_FILE = OUT_DIR / "l1-classes.md"


def render_l1_classes(data: dict) -> str:
    classes = data.get("classes", [])
    abstract = sum(1 for c in classes if c.get("abstract"))
    concrete = len(classes) - abstract
    version = data.get("metadata", {}).get("version", "unknown")

    lines = [
        "<!-- AUTO-GENERATED by scripts/generate_glossary.py — do not edit by hand. -->",
        "",
        f"**L1 Core v{version} — {len(classes)} classes ({concrete} concrete + {abstract} abstract)**",
        "",
        "| ID | 中文 | English | Parent | Abstract |",
        "|:---|:---|:---|:---|:---:|",
    ]
    for c in classes:
        cid = c.get("id", "")
        zh = c.get("label_zh", "")
        en = c.get("label_en", "")
        parent = c.get("parent")
        is_abs = "✓" if c.get("abstract") else ""
        parent_cell = f"`{parent}`" if parent else "—"
        lines.append(f"| `{cid}` | {zh} | {en} | {parent_cell} | {is_abs} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if not L1_PATH.exists():
        print(f"L1 file missing: {L1_PATH}", file=sys.stderr)
        return 1

    data = json.loads(L1_PATH.read_text(encoding="utf-8"))
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(render_l1_classes(data) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_FILE.relative_to(ROOT)} ({len(data.get('classes', []))} classes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
